spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


#  datasource:
#    url: jdbc:h2:file:/data/dict
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update


  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/dict_db
    username: root
    password: root
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
#    generate-ddl: true
    generate-ddl: false
    hibernate:
#      ddl-auto: create
#      ddl-auto: update
#      ddl-auto: drop
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
